#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# SSH VPN Tunnel Server — Container Entrypoint
# Configures and starts the SSH VPN server from environment variables
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
section() { echo -e "\n${BOLD}── $* ────────────────────────────────────────────${RESET}"; }

# ── Resolve environment variables ─────────────────────────────────────────────
SSH_PORT="${SSH_PORT:-2222}"
TUN_DEV="${TUN_DEV:-tun0}"
TUN_LOCAL_IP="${TUN_LOCAL_IP:-10.10.10.2}"
TUN_REMOTE_IP="${TUN_REMOTE_IP:-10.10.10.1}"
TUN_NETMASK="${TUN_NETMASK:-255.255.255.252}"
TUN_MTU="${TUN_MTU:-1340}"
LAN_SUBNET="${LAN_SUBNET:-192.168.0.0/24}"
LAN_IFACE="${LAN_IFACE:-}"
ENABLE_NAT="${ENABLE_NAT:-yes}"
# Note: FULL_TUNNEL is a client-side routing decision.
# This server always NATs all tun traffic (when ENABLE_NAT=yes).
# Clients control split vs full tunnel by which routes they add after connecting.
SSH_AUTHORIZED_KEYS="${SSH_AUTHORIZED_KEYS:-}"
ALLOW_PASSWORD_AUTH="${ALLOW_PASSWORD_AUTH:-no}"
SSH_ROOT_PASSWORD="${SSH_ROOT_PASSWORD:-}"
# Password for the web admin panel (PAM auth — sets root Linux account password)
# Set VPN_ADMIN_PASSWORD=<password> to enable admin UI login with username 'root'
VPN_ADMIN_PASSWORD="${VPN_ADMIN_PASSWORD:-}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"
TUN_MONITOR_INTERVAL="${TUN_MONITOR_INTERVAL:-5}"

# Gateway reverse tunnel
GW_ENABLED="${GW_ENABLED:-no}"
GW_HOST="${GW_HOST:-}"
GW_PORT="${GW_PORT:-22}"
GW_USER="${GW_USER:-root}"
GW_SSH_KEY_FILE="${GW_SSH_KEY_FILE:-}"
GW_SSH_KEY="${GW_SSH_KEY:-}"
GW_SSH_KEY_B64="${GW_SSH_KEY_B64:-no}"
GW_PASSWORD="${GW_PASSWORD:-}"
GW_EXPOSED_PORT="${GW_EXPOSED_PORT:-2255}"
GW_PUBLIC_PORT="${GW_PUBLIC_PORT:-${GW_EXPOSED_PORT}}"
GW_BIND_ADDR="${GW_BIND_ADDR:-0.0.0.0}"
GW_RECONNECT_INTERVAL="${GW_RECONNECT_INTERVAL:-30}"

# Multi-user: newline-separated "username:pubkey" pairs
# Each user gets a unique tun slot (1–253), IPs 10.10.<N>.1/10.10.<N>.2
VPN_USERS="${VPN_USERS:-}"
USERS_DIR="/etc/vpn/users"

# Extract tun device number (tun0 → 0, tun100 → 100) — used for legacy single-user mode
TUN_NUM=$(echo "$TUN_DEV" | grep -oE '[0-9]+$' || echo "0")

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}"
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║     SSH VPN Tunnel Server  v1.0              ║"
echo "  ║     registry.app.circle360.net               ║"
echo "  ╚══════════════════════════════════════════════╝"
echo -e "${RESET}"

# ── Step 1: /dev/net/tun check ────────────────────────────────────────────────
section "1. TUN Device"
if [[ ! -c /dev/net/tun ]]; then
    error "/dev/net/tun not found!"
    error "Run container with:"
    error "  --device /dev/net/tun:/dev/net/tun"
    error "  --cap-add NET_ADMIN"
    exit 1
fi
success "/dev/net/tun available"

# ── Step 2: SSH Host Keys ─────────────────────────────────────────────────────
section "2. SSH Host Keys"
mkdir -p /etc/ssh/server_keys
for key_type in rsa ecdsa ed25519; do
    key_file="/etc/ssh/server_keys/ssh_host_${key_type}_key"
    if [[ ! -f "$key_file" ]]; then
        ssh-keygen -t "$key_type" -f "$key_file" -N "" -q
        info "Generated ${key_type} host key"
    fi
done
success "SSH host keys ready at /etc/ssh/server_keys/"

# ── Step 3: sshd_config ───────────────────────────────────────────────────────
section "3. SSH Configuration"
cat > /etc/ssh/sshd_config << EOF
# SSH VPN Server — generated by entrypoint.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')

Port ${SSH_PORT}

# Host keys (persisted via Docker volume)
HostKey /etc/ssh/server_keys/ssh_host_rsa_key
HostKey /etc/ssh/server_keys/ssh_host_ecdsa_key
HostKey /etc/ssh/server_keys/ssh_host_ed25519_key

# ── Authentication ────────────────────────────────────────────────────────────
PermitRootLogin yes
PubkeyAuthentication yes
AuthorizedKeysFile /root/.ssh/authorized_keys
PasswordAuthentication ${ALLOW_PASSWORD_AUTH}
ChallengeResponseAuthentication no
UsePAM no

# ── Tunneling (required for VPN) ──────────────────────────────────────────────
# PermitTunnel yes  → allows SSH -w tun device creation
# point-to-point    → layer 3 (IP) tun devices (not ethernet tap)
PermitTunnel point-to-point
AllowTcpForwarding yes
GatewayPorts yes

# ── Security ──────────────────────────────────────────────────────────────────
X11Forwarding no
UseDNS no
PrintMotd no
AddressFamily inet

# ── Connection keepalive ──────────────────────────────────────────────────────
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 3

# ── Limits ────────────────────────────────────────────────────────────────────
MaxStartups 10:30:100
MaxSessions 20

# ── Logging ───────────────────────────────────────────────────────────────────
LogLevel ${LOG_LEVEL}
SyslogFacility AUTH
EOF

success "sshd_config written (port ${SSH_PORT}, LogLevel ${LOG_LEVEL})"

# ── Step 4: Authorized Keys ───────────────────────────────────────────────────
section "4. Authorized Keys"
mkdir -p /root/.ssh
chmod 700 /root/.ssh

AUTH_KEYS="/root/.ssh/authorized_keys"
touch "${AUTH_KEYS}"

if [[ -n "$SSH_AUTHORIZED_KEYS" ]]; then
    key_count=0
    while IFS= read -r line; do
        # Skip blank lines and comments
        [[ -z "${line//[[:space:]]/}" ]] && continue
        [[ "$line" == \#* ]] && continue

        if echo "$line" | grep -qE '^(ssh-|ecdsa-|sk-)'; then
            # Plain public key — prefix with tunnel restriction
            formatted_key="tunnel=\"${TUN_NUM}\" ${line}"
        elif echo "$line" | grep -q 'tunnel='; then
            # Already has a tunnel option — use as-is
            formatted_key="$line"
        else
            # Has other options (no-pty etc) but no tunnel — prepend tunnel
            formatted_key="tunnel=\"${TUN_NUM}\",${line}"
        fi

        if ! grep -Fxq "$formatted_key" "${AUTH_KEYS}"; then
            echo "$formatted_key" >> "${AUTH_KEYS}"
            (( key_count++ )) || true
        fi
    done <<< "$SSH_AUTHORIZED_KEYS"

    success "Configured ${key_count} key(s) with tunnel=\"${TUN_NUM}\" permission"
else
    warn "SSH_AUTHORIZED_KEYS is empty — no client keys loaded yet"
    warn "Add keys at runtime:"
    warn "  docker exec <container> bash -c 'echo \"tunnel=\\\"${TUN_NUM}\\\" ssh-ed25519 AAAA...\" >> ${AUTH_KEYS}'"
fi

chmod 600 "${AUTH_KEYS}"

# ── Step 4b: User config directory + legacy default.conf ─────────────────────
section "4b. User Config Directory"
mkdir -p /etc/vpn/users

# Write a default.conf so tun-monitor can configure the legacy tun device
# when SSH_AUTHORIZED_KEYS is used (single-user / backward-compat mode).
if [[ -n "$SSH_AUTHORIZED_KEYS" ]]; then
    cat > /etc/vpn/users/default.conf << EOF
# Legacy single-user config — generated by entrypoint.sh
# Created: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
USERNAME=default
TUN_NUM=${TUN_NUM}
TUN_LOCAL_IP=${TUN_LOCAL_IP}
TUN_REMOTE_IP=${TUN_REMOTE_IP}
EOF
    chmod 600 /etc/vpn/users/default.conf
    success "Legacy user config written (tun${TUN_NUM}: ${TUN_LOCAL_IP} <-> ${TUN_REMOTE_IP})"
fi

# ── Step 4c: VPN_USERS — multi-user provisioning ──────────────────────────────
section "4c. VPN Users (multi-user)"
if [[ -n "$VPN_USERS" ]]; then
    vpn_user_count=0
    while IFS= read -r vpn_line; do
        # Trim leading whitespace
        vpn_line="${vpn_line#"${vpn_line%%[! $'\t']*}"}"
        [[ -z "$vpn_line" || "$vpn_line" == \#* ]] && continue
        vpn_username="${vpn_line%%:*}"
        vpn_pubkey="${vpn_line#*:}"
        vpn_pubkey="${vpn_pubkey# }"   # strip one leading space if present
        conf_file="${USERS_DIR}/${vpn_username}.conf"
        if [[ -f "$conf_file" ]]; then
            # Container restarted — conf persists on volume but authorized_keys
            # was cleared in Step 4. Re-sync the key entry without changing the slot.
            slot=$(grep '^TUN_NUM=' "$conf_file" | cut -d= -f2)
            sed -i "/vpn-user:${vpn_username}\b/d" /root/.ssh/authorized_keys 2>/dev/null || true
            echo "tunnel=\"${slot}\" ${vpn_pubkey} vpn-user:${vpn_username}" >> /root/.ssh/authorized_keys
            info "VPN user '${vpn_username}' re-synced (tun${slot} — persisted from previous run)"
            (( vpn_user_count++ )) || true
        elif /usr/local/bin/manage-users.sh add "$vpn_username" "$vpn_pubkey"; then
            (( vpn_user_count++ )) || true
        else
            warn "Failed to add VPN user: ${vpn_username} (check key format)"
        fi
    done <<< "$VPN_USERS"
    success "Added ${vpn_user_count} VPN user(s) from VPN_USERS"
else
    info "VPN_USERS not set — add users at runtime:"
    info "  docker exec <container> manage-users.sh add <username> \"<pubkey>\""
fi

# ── Step 5: Root Password ─────────────────────────────────────────────────────
if [[ -n "$SSH_ROOT_PASSWORD" ]]; then
    if [[ "$ALLOW_PASSWORD_AUTH" != "yes" ]]; then
        warn "SSH_ROOT_PASSWORD set but ALLOW_PASSWORD_AUTH=no → password login still disabled"
    else
        echo "root:${SSH_ROOT_PASSWORD}" | chpasswd
        success "Root password set (password auth enabled)"
    fi
fi

# ── Step 5b: Admin UI Password ────────────────────────────────────────────────
# Sets the root Linux account password for PAM-based web admin login.
# Login at http://<host>:8080 with username 'root' and this password.
if [[ -n "$VPN_ADMIN_PASSWORD" ]]; then
    echo "root:${VPN_ADMIN_PASSWORD}" | chpasswd
    success "Admin UI password set — log in at :8080 with username 'root'"
else
    warn "VPN_ADMIN_PASSWORD not set — web admin login will fail"
    warn "Set VPN_ADMIN_PASSWORD=<password> to enable admin UI access"
fi

# ── Step 6: IP Forwarding ─────────────────────────────────────────────────────
section "5. IP Forwarding"
# /proc/sys is read-only inside Docker — must use sysctl(8), not echo.
# docker-compose sysctls: already sets this before entrypoint runs;
# the sysctl call below is a safety net in case it wasn't applied.
sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1 || true
sysctl -w net.ipv6.conf.all.forwarding=1 > /dev/null 2>&1 || true

# Verify — read current value directly (read-only /proc is always readable)
IP_FWD=$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null || echo "unknown")
if [[ "${IP_FWD}" == "1" ]]; then
    success "IPv4 forwarding enabled (ip_forward=1)"
else
    warn "ip_forward=${IP_FWD} — NAT may not work"
    warn "Add to docker-compose sysctls: net.ipv4.ip_forward: '1'"
    warn "Or run host: sudo sysctl -w net.ipv4.ip_forward=1"
fi

# ── Step 7: iptables NAT ──────────────────────────────────────────────────────
section "6. iptables NAT"
if [[ "${ENABLE_NAT}" == "yes" ]]; then
    # Auto-detect egress interface if not specified
    if [[ -z "$LAN_IFACE" ]]; then
        LAN_IFACE=$(ip route show default 2>/dev/null | awk '/default/{print $5}' | head -1)
        if [[ -z "$LAN_IFACE" ]]; then
            LAN_IFACE="eth0"
            warn "Could not detect default route interface — assuming eth0"
        fi
    fi
    info "NAT egress interface: ${LAN_IFACE}"

    # MASQUERADE: VPN client traffic exits on LAN interface as server IP
    iptables -t nat -C POSTROUTING -o "${LAN_IFACE}" -j MASQUERADE 2>/dev/null || \
        iptables -t nat -A POSTROUTING -o "${LAN_IFACE}" -j MASQUERADE

    # FORWARD: tun → LAN
    iptables -C FORWARD -i 'tun+' -o "${LAN_IFACE}" -j ACCEPT 2>/dev/null || \
        iptables -A FORWARD -i 'tun+' -o "${LAN_IFACE}" -j ACCEPT

    # FORWARD: LAN → tun (established/related only)
    iptables -C FORWARD -i "${LAN_IFACE}" -o 'tun+' \
        -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || \
        iptables -A FORWARD -i "${LAN_IFACE}" -o 'tun+' \
        -m state --state RELATED,ESTABLISHED -j ACCEPT

    # TCP MSS clamping: clamp SYN packets to path MTU to prevent fragmentation
    # inside the SSH tunnel (tun MTU is lower than physical MTU).
    iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN \
        -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
        iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN \
        -j TCPMSS --clamp-mss-to-pmtu
    iptables -t mangle -C OUTPUT -p tcp --tcp-flags SYN,RST SYN \
        -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null || \
        iptables -t mangle -A OUTPUT -p tcp --tcp-flags SYN,RST SYN \
        -j TCPMSS --clamp-mss-to-pmtu

    success "iptables MASQUERADE configured on ${LAN_IFACE}"
else
    warn "NAT disabled (ENABLE_NAT=no) — clients will not have internet access via this server"
fi

# ── Step 8: Summary ───────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}  ┌─ VPN Server Ready ──────────────────────────────────┐${RESET}"
echo -e "${BOLD}${GREEN}  │${RESET}  SSH Port:        ${BOLD}${SSH_PORT}${RESET}"
echo -e "${BOLD}${GREEN}  │${RESET}  Tun Device:      ${BOLD}${TUN_DEV}${RESET} (tunnel #${TUN_NUM})"
echo -e "${BOLD}${GREEN}  │${RESET}  Server tun IP:   ${BOLD}${TUN_LOCAL_IP}${RESET}"
echo -e "${BOLD}${GREEN}  │${RESET}  Client tun IP:   ${BOLD}${TUN_REMOTE_IP}${RESET} (peer)"
echo -e "${BOLD}${GREEN}  │${RESET}  Tunnel MTU:      ${BOLD}${TUN_MTU}${RESET}"
echo -e "${BOLD}${GREEN}  │${RESET}  LAN Subnet:      ${BOLD}${LAN_SUBNET}${RESET}"
echo -e "${BOLD}${GREEN}  │${RESET}  NAT:             ${BOLD}${ENABLE_NAT}${RESET}"
echo -e "  ${BOLD}${GREEN}  │${RESET}  Tunnel mode:     client-controlled (split=add LAN route | full=add default route)"
echo -e "${BOLD}${GREEN}  │${RESET}  Auth:            ${BOLD}Key-based${RESET}${ALLOW_PASSWORD_AUTH:+ / Password}"
echo -e "${BOLD}${GREEN}  └─────────────────────────────────────────────────────┘${RESET}"
echo ""
echo -e "  ${BOLD}Client connect examples:${RESET}"
echo -e "  # Raw SSH tunnel (Linux/WSL2/macOS):"
echo -e "  sudo ssh -w ${TUN_NUM}:${TUN_NUM} -o Tunnel=point-to-point \\"
echo -e "       -i ~/.ssh/id_ed25519 -p ${SSH_PORT} root@<server> -f -N"
echo -e ""
echo -e "  # NetworkManager (nm-ssh) — use vpn-connect-nmcli or nmcli con up <name>"
echo -e "  # Windows WSL2: run above command inside WSL2 then:"
echo -e "  #   NET ROUTE ADD 10.10.10.0 MASK 255.255.255.252 <WSL2-IP> (admin CMD)"
echo -e "  #   NET ROUTE ADD ${LAN_SUBNET%/*} MASK 255.255.255.0 <WSL2-IP>"
echo -e ""
echo -e "  ${BOLD}Routing modes (client-side):${RESET}"
echo -e "  Split tunnel:  sudo ip route add ${LAN_SUBNET} via ${TUN_REMOTE_IP} dev ${TUN_DEV}"
echo -e "  Full tunnel:   sudo ip route add 0.0.0.0/1 via ${TUN_REMOTE_IP} dev ${TUN_DEV}"
echo -e "                 sudo ip route add 128.0.0.0/1 via ${TUN_REMOTE_IP} dev ${TUN_DEV}"
echo ""

# ── Step 9: Start Tun Monitor ─────────────────────────────────────────────────
section "7. Starting Tun Monitor"
# tun-monitor reads user configs from /etc/vpn/users/*.conf dynamically
export TUN_MTU TUN_MONITOR_INTERVAL
/usr/local/bin/tun-monitor.sh >> /var/log/vpn/tun-monitor.log 2>&1 &
TUN_MONITOR_PID=$!
success "Tun monitor started (PID ${TUN_MONITOR_PID}) → /var/log/vpn/tun-monitor.log"

# ── Step 10: Gateway Reverse Tunnel ──────────────────────────────────────────
section "8. Gateway Reverse Tunnel"
if [[ "${GW_ENABLED}" == "yes" ]]; then
    if [[ -z "${GW_HOST}" ]]; then
        error "GW_ENABLED=yes but GW_HOST is not set — skipping gateway tunnel"
    else
        info "Starting gateway tunnel: ${GW_USER}@${GW_HOST}:${GW_PORT}"
        info "  ${GW_HOST}:${GW_EXPOSED_PORT} → this container:${SSH_PORT}"

        export GW_ENABLED GW_HOST GW_PORT GW_USER \
               GW_SSH_KEY_FILE GW_SSH_KEY GW_SSH_KEY_B64 GW_PASSWORD \
               GW_EXPOSED_PORT GW_PUBLIC_PORT GW_BIND_ADDR GW_RECONNECT_INTERVAL SSH_PORT

        /usr/local/bin/gateway-tunnel.sh >> /var/log/vpn/gateway-tunnel.log 2>&1 &
        GW_PID=$!
        success "Gateway tunnel started (PID ${GW_PID}) → /var/log/vpn/gateway-tunnel.log"
        echo ""
        echo -e "  ${BOLD}VPN clients connect via gateway:${RESET}"
        echo -e "  sudo ssh -w 0:0 -o Tunnel=point-to-point \\"
        echo -e "       -i ~/.ssh/id_ed25519 -p ${GW_PUBLIC_PORT} \\"
        echo -e "       root@${GW_HOST} -f -N"
    fi
else
    info "GW_ENABLED=no — set GW_ENABLED=yes to expose this server via a public gateway"
fi

# ── Step 11: Start vpn-api control plane ─────────────────────────────────────
section "10. Starting vpn-api Control Plane"
if command -v vpn-api &>/dev/null; then
    VPN_API_LISTEN="${VPN_API_LISTEN:-:8080}"
    VPN_AUDIT_LOG="${VPN_AUDIT_LOG:-/var/log/vpn/audit.log}"
    export VPN_API_LISTEN VPN_API_PUBLIC VPN_SESSION_SECRET \
           VPN_OTP_SHARED_SECRET VPN_OTP_TOKEN_TTL VPN_AUDIT_LOG
    vpn-api >> /var/log/vpn/api.log 2>&1 &
    API_PID=$!
    success "vpn-api started (PID ${API_PID}) → ${VPN_API_LISTEN} | log: /var/log/vpn/api.log"
else
    warn "vpn-api binary not found — admin web UI not available"
fi

# ── Step 12: Start SSH Daemon ─────────────────────────────────────────────────
section "11. Starting SSH Daemon"
info "SSH listening on port ${SSH_PORT} — waiting for VPN clients..."
echo ""

# exec replaces this shell with sshd as PID 1
# -D: don't daemonize   -e: log to stderr (visible via docker logs)
exec /usr/sbin/sshd -D -e
